#!/usr/bin/env ruby
# This script was generated by ChatGPT for testing the Appcircle Custom Script from Git Component.
# https://github.com/appcircleio/appcircle-custom-script-from-git-component

require 'fileutils'

# Read required environment variable
required_env = ENV['REQUIRED_VAR']

if required_env.nil? || required_env.strip.empty?
  puts "Missing REQUIRED_VAR environment variable.".red rescue puts "Missing REQUIRED_VAR environment variable."
  exit 1
end

# Print all arguments
puts "Arguments received: #{ARGV.join(' ')}"

# Simulate writing to a file
File.open("ruby_env_output.txt", "w") do |f|
  f.puts "REQUIRED_VAR=#{required_env}"
end

# Simulate optional failure with --fail flag
if ARGV.include?('--fail')
  puts "Simulated failure due to --fail flag."
  exit 1
end

puts "Ruby script completed successfully."
