// This script was generated by ChatGPT for testing the component at:
// https://github.com/appcircleio/appcircle-custom-script-from-git-component

import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;

public class TestScript {
    public static void main(String[] args) {
        System.out.println("Java script started.");

        // 1. Print args
        System.out.println("Received arguments: " + Arrays.toString(args));

        // 2. Read env var
        String envVar = System.getenv("TEST_ENV_VAR");
        if (envVar == null || envVar.isEmpty()) {
            System.err.println("TEST_ENV_VAR is not set.");
        } else {
            System.out.println("TEST_ENV_VAR = " + envVar);
        }

        // 3. Write to file
        try (FileWriter writer = new FileWriter("java_output.txt")) {
            writer.write("Hello from Java at " + System.currentTimeMillis() + "\n");
            writer.write("Arguments: " + Arrays.toString(args));
            System.out.println("Successfully wrote to java_output.txt");
        } catch (IOException e) {
            System.err.println("Failed to write file: " + e.getMessage());
        }

        // 4. Simulate failure with flag
        if (Arrays.asList(args).contains("--fail")) {
            System.err.println("Simulating failure because --fail flag is present.");
            System.exit(1);
        }

        System.out.println("Java script finished successfully.");
    }
}
