#!/usr/bin/env python3
# This script was generated by ChatGPT for testing the Appcircle Custom Script from Git Component.
# https://github.com/appcircleio/appcircle-custom-script-from-git-component

import os
import sys
import json

def main():
    # Print all arguments
    print("Arguments received:", sys.argv[1:])

    # Read environment variable
    json_input = os.environ.get("TEST_JSON_VAR")

    if not json_input:
        print("Missing TEST_JSON_VAR environment variable.")
        sys.exit(1)

    # Try parsing the JSON
    try:
        parsed = json.loads(json_input)
        print("Parsed JSON:", parsed)
    except json.JSONDecodeError:
        print("Invalid JSON in TEST_JSON_VAR. Failing the script.")
        sys.exit(1)

    # Write to file
    with open("python_env_output.txt", "w") as f:
        f.write("JSON_KEYS=" + ",".join(parsed.keys()))

    # Optional simulated failure
    if "--fail" in sys.argv:
        print("Simulated failure due to --fail flag.")
        sys.exit(1)

    print("Python script completed successfully.")

if __name__ == "__main__":
    main()
