#!/usr/bin/env perl
# This script was generated by ChatGPT for testing the Appcircle Custom Script from Git Component.
# https://github.com/appcircleio/appcircle-custom-script-from-git-component

use strict;
use warnings;

# Print all received arguments
print "Arguments received: @ARGV\n";

# Read environment variable
my $test_var = $ENV{"TEST_ENV_VAR"} // "Not set";
print "TEST_ENV_VAR: $test_var\n";

# Write output to a file
open(my $fh, '>', 'perl_output.txt') or die "Cannot open file: $!";
print $fh "TEST_ENV_VAR=$test_var\n";
close($fh);

# Simulate failure if --fail is passed
if (grep { $_ eq "--fail" } @ARGV) {
    print "Simulated failure due to --fail flag.\n";
    exit 1;
}

print "Perl script completed successfully.\n";

