#!/usr/bin/env bash
# This script was generated by ChatGPT for testing the Appcircle Custom Script from Git Component.
# https://github.com/appcircleio/appcircle-custom-script-from-git-component

set -e

echo "Arguments received: $@"

echo "TEST_ENV_VAR: ${TEST_ENV_VAR:-Not set}"

# Write TEST_ENV_VAR to output file
echo "TEST_ENV_VAR=${TEST_ENV_VAR}" > bash_output.txt

# Simulate failure if '--fail' is passed
for arg in "$@"; do
  if [[ "$arg" == "--fail" ]]; then
    echo "Simulated failure due to --fail flag."
    exit 1
  fi
done

echo "Bash script completed successfully."
